export const ADMIN_EXPERIENCES_REQUEST = 'ADMIN_EXPERIENCES_REQUEST'
export const ADMIN_EXPERIENCES_SUCCESS = 'ADMIN_EXPERIENCES_SUCCESS'
export const ADMIN_EXPERIENCES_FAIL = 'ADMIN_EXPERIENCES_FAIL'

export const ALL_EXPERIENCES_REQUEST = 'ALL_EXPERIENCES_REQUEST'
export const ALL_EXPERIENCES_SUCCESS = 'ALL_EXPERIENCES_SUCCESS'
export const ALL_EXPERIENCES_FAIL = 'ALL_EXPERIENCES_FAIL'

export const NEW_EXPERIENCE_REQUEST = 'NEW_EXPERIENCE_REQUEST'
export const NEW_EXPERIENCE_SUCCESS = 'NEW_EXPERIENCE_SUCCESS'
export const NEW_EXPERIENCE_RESET = 'NEW_EXPERIENCE_RESET'
export const NEW_EXPERIENCE_FAIL = 'NEW_EXPERIENCE_FAIL'

export const DELETE_EXPERIENCE_REQUEST = 'DELETE_EXPERIENCE_REQUEST'
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS'
export const DELETE_EXPERIENCE_RESET = 'DELETE_EXPERIENCE_RESET'
export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL'

export const UPDATE_EXPERIENCE_REQUEST = 'UPDATE_EXPERIENCE_REQUEST'
export const UPDATE_EXPERIENCE_SUCCESS = 'UPDATE_EXPERIENCE_SUCCESS'
export const UPDATE_EXPERIENCE_RESET = 'UPDATE_EXPERIENCE_RESET'
export const UPDATE_EXPERIENCE_FAIL = 'UPDATE_EXPERIENCE_FAIL'

export const EXPERIENCE_DETAILS_REQUEST = 'EXPERIENCE_DETAILS_REQUEST'
export const EXPERIENCE_DETAILS_SUCCESS = 'EXPERIENCE_DETAILS_SUCCESS'
export const EXPERIENCE_DETAILS_FAIL = 'EXPERIENCE_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const MY_EXPERIENCES_REQUEST = 'MY_EXPERIENCES_REQUEST'
export const MY_EXPERIENCES_SUCCESS = 'MY_EXPERIENCES_SUCCESS'
export const MY_EXPERIENCES_FAIL = 'MY_EXPERIENCES_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'