export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE'
export const REMOVE_ITEM_FAVOURITE = 'REMOVE_ITEM_FAVOURITE'

export const ADD_LODGING_TO_FAVOURITE = 'ADD_LODGING_TO_FAVOURITE'
export const REMOVE_LODGING_FAVOURITE = 'REMOVE_LODGING_ITEM_FAVOURITE'

export const ADD_TRANSPORT_TO_FAVOURITE = 'ADD_TRANSPORT_TO_FAVOURITE'
export const REMOVE_TRANSPORT_FAVOURITE = 'REMOVE_TRANSPORT_FAVOURITE'

export const ADD_RESTAURANT_TO_FAVOURITE = 'ADD_RESTAURANT_TO_FAVOURITE'
export const REMOVE_RESTAURANT_FAVOURITE = 'REMOVE_RESTAURANT_FAVOURITE'

export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'