export const ADMIN_LODGINGS_REQUEST = 'ADMIN_LODGINGS_REQUEST'
export const ADMIN_LODGINGS_SUCCESS = 'ADMIN_LODGINGS_SUCCESS'
export const ADMIN_LODGINGS_FAIL = 'ADMIN_LODGINGS_FAIL'

export const ALL_LODGINGS_REQUEST = 'ALL_LODGINGS_REQUEST'
export const ALL_LODGINGS_SUCCESS = 'ALL_LODGINGS_SUCCESS'
export const ALL_LODGINGS_FAIL = 'ALL_LODGINGS_FAIL'

export const NEW_LODGING_REQUEST = 'NEW_LODGING_REQUEST'
export const NEW_LODGING_SUCCESS = 'NEW_LODGING_SUCCESS'
export const NEW_LODGING_RESET = 'NEW_LODGING_RESET'
export const NEW_LODGING_FAIL = 'NEW_LODGING_FAIL'

export const DELETE_LODGING_REQUEST = 'DELETE_LODGING_REQUEST'
export const DELETE_LODGING_SUCCESS = 'DELETE_LODGING_SUCCESS'
export const DELETE_LODGING_RESET = 'DELETE_LODGING_RESET'
export const DELETE_LODGING_FAIL = 'DELETE_LODGING_FAIL'

export const UPDATE_LODGING_REQUEST = 'UPDATE_LODGING_REQUEST'
export const UPDATE_LODGING_SUCCESS = 'UPDATE_LODGING_SUCCESS'
export const UPDATE_LODGING_RESET = 'UPDATE_LODGING_RESET'
export const UPDATE_LODGING_FAIL = 'UPDATE_LODGING_FAIL'

export const LODGING_DETAILS_REQUEST = 'LODGING_DETAILS_REQUEST'
export const LODGING_DETAILS_SUCCESS = 'LODGING_DETAILS_SUCCESS'
export const LODGING_DETAILS_FAIL = 'LODGING_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'


export const MY_LODGINGS_REQUEST = 'MY_LODGINGS_REQUEST'
export const MY_LODGINGS_SUCCESS = 'MY_LODGINGS_SUCCESS'
export const MY_LODGINGS_FAIL = 'MY_LODGINGS_FAIL'

//delete review missing

export const CLEAR_ERRORS = 'CLEAR_ERRORS'