export const ADMIN_RESTAURANTS_REQUEST = 'ADMIN_RESTAURANTS_REQUEST'
export const ADMIN_RESTAURANTS_SUCCESS = 'ADMIN_RESTAURANTS_SUCCESS'
export const ADMIN_RESTAURANTS_FAIL = 'ADMIN_RESTAURANTS_FAIL'

export const ALL_RESTAURANTS_REQUEST = 'ALL_RESTAURANTS_REQUEST'
export const ALL_RESTAURANTS_SUCCESS = 'ALL_RESTAURANTS_SUCCESS'
export const ALL_RESTAURANTS_FAIL = 'ALL_RESTAURANTS_FAIL'

export const NEW_RESTAURANT_REQUEST = 'NEW_RESTAURANT_REQUEST'
export const NEW_RESTAURANT_SUCCESS = 'NEW_RESTAURANT_SUCCESS'
export const NEW_RESTAURANT_RESET = 'NEW_RESTAURANT_RESET'
export const NEW_RESTAURANT_FAIL = 'NEW_RESTAURANT_FAIL'

export const DELETE_RESTAURANT_REQUEST = 'DELETE_RESTAURANT_REQUEST'
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS'
export const DELETE_RESTAURANT_RESET = 'DELETE_RESTAURANT_RESET'
export const DELETE_RESTAURANT_FAIL = 'DELETE_RESTAURANT_FAIL'

export const UPDATE_RESTAURANT_REQUEST = 'UPDATE_RESTAURANT_REQUEST'
export const UPDATE_RESTAURANT_SUCCESS = 'UPDATE_RESTAURANT_SUCCESS'
export const UPDATE_RESTAURANT_RESET = 'UPDATE_RESTAURANT_RESET'
export const UPDATE_RESTAURANT_FAIL = 'UPDATE_RESTAURANT_FAIL'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST'
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS'
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'


export const MY_RESTAURANTS_REQUEST = 'MY_RESTAURANTS_REQUEST'
export const MY_RESTAURANTS_SUCCESS = 'MY_RESTAURANTS_SUCCESS'
export const MY_RESTAURANTS_FAIL = 'MY_RESTAURANTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'