export const ADMIN_TRANSPORTS_REQUEST = 'ADMIN_TRANSPORTS_REQUEST'
export const ADMIN_TRANSPORTS_SUCCESS = 'ADMIN_TRANSPORTS_SUCCESS'
export const ADMIN_TRANSPORTS_FAIL = 'ADMIN_TRANSPORTS_FAIL'

export const ALL_TRANSPORTS_REQUEST = 'ALL_TRANSPORTS_REQUEST'
export const ALL_TRANSPORTS_SUCCESS = 'ALL_TRANSPORTS_SUCCESS'
export const ALL_TRANSPORTS_FAIL = 'ALL_TRANSPORTS_FAIL'

export const NEW_TRANSPORT_REQUEST = 'NEW_TRANSPORT_REQUEST'
export const NEW_TRANSPORT_SUCCESS = 'NEW_TRANSPORT_SUCCESS'
export const NEW_TRANSPORT_RESET = 'NEW_TRANSPORT_RESET'
export const NEW_TRANSPORT_FAIL = 'NEW_TRANSPORT_FAIL'

export const DELETE_TRANSPORT_REQUEST = 'DELETE_TRANSPORT_REQUEST'
export const DELETE_TRANSPORT_SUCCESS = 'DELETE_TRANSPORT_SUCCESS'
export const DELETE_TRANSPORT_RESET = 'DELETE_TRANSPORT_RESET'
export const DELETE_TRANSPORT_FAIL = 'DELETE_TRANSPORT_FAIL'

export const UPDATE_TRANSPORT_REQUEST = 'UPDATE_TRANSPORT_REQUEST'
export const UPDATE_TRANSPORT_SUCCESS = 'UPDATE_TRANSPORT_SUCCESS'
export const UPDATE_TRANSPORT_RESET = 'UPDATE_TRANSPORT_RESET'
export const UPDATE_TRANSPORT_FAIL = 'UPDATE_TRANSPORT_FAIL'

export const TRANSPORT_DETAILS_REQUEST = 'TRANSPORT_DETAILS_REQUEST'
export const TRANSPORT_DETAILS_SUCCESS = 'TRANSPORT_DETAILS_SUCCESS'
export const TRANSPORT_DETAILS_FAIL = 'TRANSPORT_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const MY_TRANSPORTS_REQUEST = 'MY_TRANSPORTS_REQUEST'
export const MY_TRANSPORTS_SUCCESS = 'MY_TRANSPORTS_SUCCESS'
export const MY_TRANSPORTS_FAIL = 'MY_TRANSPORTS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'